src/Entity/Competition.php
<?php declare (strict_types=1);

namespace App\Entity;

use ApiPlatform\Metadata\Post;
use ApiPlatform\Metadata\GetCollection;
use ApiPlatform\Metadata\Put;
use ApiPlatform\Metadata\Get;
use ApiPlatform\Metadata\ApiResource;
use App\Repository\CompetitionRepository;
use Symfony\Component\Serializer\Annotation\Context;
use Symfony\Component\Serializer\Annotation\Groups;
use Symfony\Component\Serializer\Normalizer\DateTimeNormalizer;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ApiResource(
    description: 'Typ sutaze v bull sportoch',
    operations: [
        new Get(security: 'is_granted("ROLE_USER")'),
        new Put(security: 'is_granted("ROLE_ADMIN")'),
        new GetCollection(security: 'is_granted("ROLE_USER")'),
        new Post(security: 'is_granted("ROLE_ADMIN")')
    ],
    normalizationContext: [
        'groups' => ['competition:read']
    ],
    denormalizationContext: [
        'groups' => ['competition:write']]
)]
#[ORM\Entity(repositoryClass: CompetitionRepository::class)]
class Competition
{
    /**
     * @throws \Exception
     */
    public function __construct()
    {
        $this->created_at = new \DateTimeImmutable('now', new \DateTimeZone('Europe/Bratislava'));
    }

    #[ORM\Id]
    #[ORM\Column(type: 'uuid', unique: true)]
    #[Groups(['competition:read', 'competition:write'])]
    private $id;

    #[Groups(['competition:read', 'competition:write', 'event:read'])]
    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private ?string $name = null;

    #[Groups(['competition:read', 'competition:write', 'event:read'])]
    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private ?string $nameSk = null;

    #[Groups(['competition:read', 'competition:write'])]
    #[ORM\Column(type: 'text', nullable: true)]
    private ?string $description = null;

    #[Groups(['competition:read', 'competition:write'])]
    #[ORM\ManyToOne(targetEntity: User::class, inversedBy: 'competitions')]
    #[ORM\JoinColumn(nullable: false)]
    #[Assert\NotBlank]
    private ?User $author = null;

    #[Groups(['competition:read'])]
    #[Context(normalizationContext: [DateTimeNormalizer::FORMAT_KEY => 'Y-m-d H:i:s'])]
    #[ORM\Column(type: 'datetime_immutable')]
    private ?\DateTimeImmutable $created_at;

    #[Groups(['competition:read', 'competition:write'])]
    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private ?string $seoDescription = null;

    #[Groups(['competition:read', 'competition:write'])]
    #[ORM\OneToOne(targetEntity: Image::class, cascade: ['persist', 'remove', 'detach'], orphanRemoval: true)]
    private ?Image $image = null;

    public function getId()
    {
        return $this->id;
    }

    public function setId($id) : self
    {
        $this->id = $id;
        return $this;
    }

    public function getName() : ?string
    {
        return $this->name;
    }

    public function setName(string $name) : self
    {
        $this->name = $name;
        return $this;
    }

    public function getNameSk() : ?string
    {
        return $this->nameSk;
    }

    public function setNameSk(string $name_sk) : self
    {
        $this->nameSk = $name_sk;
        return $this;
    }

    public function getDescription() : ?string
    {
        return $this->description;
    }

    public function setDescription(string $description) : self
    {
        $this->description = $description;
        return $this;
    }

    public function getAuthor() : ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author) : self
    {
        $this->author = $author;
        return $this;
    }

    public function getCreatedAt() : ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at) : self
    {
        $this->created_at = $created_at;
        return $this;
    }

    public function getImage() : ?Image
    {
        return $this->image;
    }

    public function setImage(?Image $image) : self
    {
        $this->image = $image;
        return $this;
    }

    public function getSeoDescription() : ?string
    {
        return $this->seoDescription;
    }

    public function setSeoDescription(?string $seoDescription) : self
    {
        $this->seoDescription = $seoDescription;
        return $this;
    }
}

src/Entity/Image.php
<?php declare (strict_types=1);

namespace App\Entity;

use ApiPlatform\Metadata\Post;
use ApiPlatform\Metadata\GetCollection;
use ApiPlatform\Metadata\Put;
use ApiPlatform\Metadata\Delete;
use ApiPlatform\Metadata\Get;
use ApiPlatform\Metadata\ApiResource;
use App\Repository\ImagesRepository;
use DateTime;
use DateTimeInterface;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;
use Symfony\Component\Uid\Uuid;

#[ApiResource(
    description: 'Zoznam obrazkov',
    operations: [
        new Get(),
        new Delete(),
        new Put(),
        new GetCollection(),
        new Post()
    ],
    normalizationContext: [
        'groups' => ['image:read']
    ],
    denormalizationContext: [
        'groups' => ['image:write']
    ]
)]
#[ORM\Entity(repositoryClass: ImagesRepository::class)]
#[ORM\HasLifecycleCallbacks]
#[ORM\Table(name: 'images')]
class Image
{
    #[ORM\Id]
    #[ORM\Column(type: 'uuid', unique: true)]
    #[Groups(['image:read', 'image:write'])]
    private Uuid $id;

    #[Groups(['image:read', 'image:write'])]
    #[ORM\Column(type: 'text')]
    private string $AWSname;

    #[Groups(['image:read', 'image:write'])]
    #[ORM\Column(type: 'text')]
    private string $name;

    #[Groups(['image:read', 'image:write'])]
    #[ORM\Column(type: 'text')]
    private string $mimeType;

    #[ORM\Column(type: 'datetime')]
    private DateTime $createdAt;

    #[ORM\Column(type: 'datetime', nullable: true)]
    private ?DateTimeInterface $updatedAt = null;

    #[ORM\PrePersist]
    public function onPrePersist(): void
    {
        $this->setCreatedAt(new \DateTime('now', new \DateTimeZone('Europe/Bratislava')));
    }

    #[ORM\PreUpdate]
    public function onPreUpdate(): void
    {
        $this->setUpdatedAt(new \DateTime('now', new \DateTimeZone('Europe/Bratislava')));
    }

    public function getId(): Uuid
    {
        return $this->id;
    }

    public function setId($id) : self
    {
        $this->id = $id;
        return $this;
    }

    public function getAWSname() : ?string
    {
        return $this->AWSname;
    }

    public function setAWSname(string $AWSname): self
    {
        $this->AWSname = $AWSname;
        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;
        return $this;
    }

    public function getMimeType(): ?string
    {
        return $this->mimeType;
    }

    public function setMimeType(string $mimeType): self
    {
        $this->mimeType = $mimeType;
        return $this;
    }

    public function getCreatedAt(): DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(DateTime $createdAt): self
    {
        $this->createdAt = $createdAt;
        return $this;
    }

    public function getUpdatedAt(): ?DateTimeInterface
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(?DateTime $updatedAt): self
    {
        $this->updatedAt = $updatedAt;
        return $this;
    }
}

src/Controller/Competitions/CompetitionsController.php
<?php declare(strict_types=1);


namespace App\Controller\Competitions;


use App\Controller\BaseController;
use App\Repository\CompetitionRepository;
use App\Support\SeoGenerator;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

class CompetitionsController extends BaseController
{
    public function __construct(private readonly CompetitionRepository $competitionRepository, private readonly SeoGenerator $seoGenerator)
    {
    }

    #[Route('/discipliny', name: 'competitions', methods: ['GET'])]
    public function index(): Response
    {
        $competitions = $this->competitionRepository->findAll();
        foreach($competitions as $competition) {
            $competition->path = $this->generateUrl(
                'competition',
                [
                    'id' => $competition->getId(),
                    'name' =>  $this->normalizeNameUrl($competition->getNameSk()),
                ]
            );
        }

        return $this->render('competitions/competitions.html.twig', [
            'aws' => $this->getParameter('aws'),
            'menu_items' => $this->getMenu(),
            'competitions' => $competitions,
        ]);
    }

    #[Route('/disciplina/{id}/{name}/', name: 'competition',  methods: ['GET']),  ]
    public function competition(string $id, string $name = null): Response
    {
        $name = str_replace('-', ' ', (string) $name);
        $competition = $this->competitionRepository->find($id);


        return $this->render('competitions/competition.html.twig', [
            'menu_items' => $this->getMenu(),
            'competition' => $competition,
            'seo' => $this->seoGenerator->seoCompetition($competition),
            'aws' => $this->getParameter('aws'),
        ]);
    }


}

templates/competitions/block_competition.html.twig
<a
    href="{{ competition.path }}"
    class=""
>
    <div class="relative p-1">
        {% if competition.image != null %}
            <img
                    src="{{ aws.url.cdn }}{{ competition.image.aWSname }}"
                    alt="{{ competition.image.name }}"
                    title="{{ competition.image.name|lower }}"
            />
        {% endif %}
        <div class="absolute bottom-12 xl:bottom-8 left-4">
            <h3 class="text-white font-bold text-5xl xl:text-2xl italic">{{ competition.name }}</h3>
        </div>
        <span class="text-xs italic">Autor: {{ competition.author.name }}</span>
    </div>
</a>

templates/competitions/competition.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
    {{ parent() }}
    {{ encore_entry_link_tags('ck-editor-content') }}
{% endblock %}

{% block meta %}
    {{ parent() }}
    {% for key,item in seo %}
        <meta name="{{ key }}" content="{{ item }}">
    {% endfor %}
{% endblock %}

{% block title %}
    {{ parent() }} - {{ competition.name }}
{% endblock %}

{% block left_side %}
    <h2 class="text-xl italic font-black mb-4 border-b-2">{{competition.name}} - {{ competition.nameSK }}</h2>
    <div class="flex flex-col">
        <img src="{{ aws.url.cdn }}{{ competition.image.aWSname }}" alt="{{ competition.image.name }}" title="{{ competition.image.name|lower }}"/>
        <div class="flex flex-row text-xs italic justify-between">
            <span>Autor: {{ competition.author.name }}</span>
            <span>Vytvorene: {{ competition.createdAt|date("d.m.Y") }}</span>
        </div>
        <div class="mt-2 ck-editor-content">
            {{ competition.description|raw}}
        </div>
    </div>
{% endblock %}

{% block upcomming_events %}
    <h3 class="text-lg italic font-black">Najbližšie udalosti</h3>
    <p class="italic font-thin">21.8.2021 Elite Bull Day 2021 II.</p>
{% endblock %}

{% block best_results %}
    <h3 class="text-lg italic font-black">Najlepšie výsledky</h3>
    <p class="italic font-thin">Boris F. Lara - weight pulling</p>
{% endblock %}

templates/competitions/competitions.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    {{ parent() }} - Disciplíny
{% endblock %}

{% block left_side %}
<h2 class="text-xl italic font-black mb-4 border-b-2">Športové disciplíny</h2>
    <div class="grid lg:grid-cols-3 md:grid-cols-2 grid-cols-1 items-stretch gap-3">
    {% for item in competitions %}
        {{ include('competitions/block_competition.html.twig', {competition: item, aws: aws}, with_context = false) }}
    {% endfor %}
    </div>
{% endblock %}

{% block right_side %}
    <h3 class="text-lg italic font-black">Najblizsie udalosti</h3>
    <p class="italic font-thin">21.8.2021 Elite Bull Day 2021 II.</p>
    <h3 class="text-lg italic font-black">Top vysledky</h3>
    <p class="italic font-thin">Boris F. Lara - weight pulling</p>
{% endblock %}